var namespace_signals =
[
    [ "ConnectionList", "class_signals_1_1_connection_list.html", "class_signals_1_1_connection_list" ],
    [ "ConnectionList< void, Args... >", "class_signals_1_1_connection_list_3_01void_00_01_args_8_8_8_01_4.html", "class_signals_1_1_connection_list_3_01void_00_01_args_8_8_8_01_4" ],
    [ "ExecutorAsync", "namespace_signals.html#class_signals_1_1_executor_async", null ],
    [ "ExecutorAsync< R(Args...)>", "class_signals_1_1_executor_async_3_01_r_07_args_8_8_8_08_4.html", "class_signals_1_1_executor_async_3_01_r_07_args_8_8_8_08_4" ],
    [ "ExecutorAuto", "namespace_signals.html#class_signals_1_1_executor_auto", null ],
    [ "ExecutorAuto< R(Args...)>", "class_signals_1_1_executor_auto_3_01_r_07_args_8_8_8_08_4.html", "class_signals_1_1_executor_auto_3_01_r_07_args_8_8_8_08_4" ],
    [ "ExecutorLazy", "namespace_signals.html#class_signals_1_1_executor_lazy", null ],
    [ "ExecutorLazy< R(Args...)>", "class_signals_1_1_executor_lazy_3_01_r_07_args_8_8_8_08_4.html", "class_signals_1_1_executor_lazy_3_01_r_07_args_8_8_8_08_4" ],
    [ "ExecutorSync", "namespace_signals.html#class_signals_1_1_executor_sync", null ],
    [ "ExecutorSync< R(Args...)>", "class_signals_1_1_executor_sync_3_01_r_07_args_8_8_8_08_4.html", "class_signals_1_1_executor_sync_3_01_r_07_args_8_8_8_08_4" ],
    [ "ExecutorThread", "namespace_signals.html#class_signals_1_1_executor_thread", null ],
    [ "ExecutorThread< R(Args...)>", "class_signals_1_1_executor_thread_3_01_r_07_args_8_8_8_08_4.html", "class_signals_1_1_executor_thread_3_01_r_07_args_8_8_8_08_4" ],
    [ "ExecutorThreadPool", "namespace_signals.html#class_signals_1_1_executor_thread_pool", null ],
    [ "ExecutorThreadPool< R(Args...)>", "class_signals_1_1_executor_thread_pool_3_01_r_07_args_8_8_8_08_4.html", "class_signals_1_1_executor_thread_pool_3_01_r_07_args_8_8_8_08_4" ],
    [ "IExecutor", "class_signals_1_1_i_executor.html", null ],
    [ "IExecutor< R(Args...)>", "class_signals_1_1_i_executor_3_01_r_07_args_8_8_8_08_4.html", "class_signals_1_1_i_executor_3_01_r_07_args_8_8_8_08_4" ],
    [ "IResult", "class_signals_1_1_i_result.html", "class_signals_1_1_i_result" ],
    [ "ISignal", "namespace_signals.html#class_signals_1_1_i_signal", null ],
    [ "ISignal< Callback(Args...)>", "class_signals_1_1_i_signal_3_01_callback_07_args_8_8_8_08_4.html", "class_signals_1_1_i_signal_3_01_callback_07_args_8_8_8_08_4" ],
    [ "MemberFunctor", "class_signals_1_1_member_functor.html", "class_signals_1_1_member_functor" ],
    [ "PSignal", "namespace_signals.html#class_signals_1_1_p_signal", null ],
    [ "PSignal< Result, Callback(Args...)>", "class_signals_1_1_p_signal_3_01_result_00_01_callback_07_args_8_8_8_08_4.html", "class_signals_1_1_p_signal_3_01_result_00_01_callback_07_args_8_8_8_08_4" ],
    [ "Queue", "class_signals_1_1_queue.html", "class_signals_1_1_queue" ],
    [ "QueueMaxSize", "class_signals_1_1_queue_max_size.html", "class_signals_1_1_queue_max_size" ],
    [ "ResultLast", "class_signals_1_1_result_last.html", "class_signals_1_1_result_last" ],
    [ "ResultQueue", "class_signals_1_1_result_queue.html", "class_signals_1_1_result_queue" ],
    [ "ResultQueue< void >", "class_signals_1_1_result_queue_3_01void_01_4.html", "class_signals_1_1_result_queue_3_01void_01_4" ],
    [ "ResultVector", "class_signals_1_1_result_vector.html", "class_signals_1_1_result_vector" ],
    [ "ResultVector< void >", "class_signals_1_1_result_vector_3_01void_01_4.html", "class_signals_1_1_result_vector_3_01void_01_4" ],
    [ "Signal", "class_signals_1_1_signal.html", "class_signals_1_1_signal" ],
    [ "ThreadPool", "class_signals_1_1_thread_pool.html", "class_signals_1_1_thread_pool" ]
];