MEDIA_SRCS:=\
  $(ProjectName)/common/libav.cpp\
  $(ProjectName)/decode/jpegturbo_decode.cpp\
  $(ProjectName)/decode/libav_decode.cpp\
  $(ProjectName)/demux/gpac_demux_mp4_simple.cpp\
  $(ProjectName)/demux/gpac_demux_mp4_full.cpp\
  $(ProjectName)/demux/libav_demux.cpp\
  $(ProjectName)/encode/jpegturbo_encode.cpp\
  $(ProjectName)/encode/libav_encode.cpp\
  $(ProjectName)/in/file.cpp\
  $(ProjectName)/in/sound_generator.cpp\
  $(ProjectName)/in/video_generator.cpp\
  $(ProjectName)/mux/gpac_mux_mp4.cpp\
  $(ProjectName)/mux/libav_mux.cpp\
  $(ProjectName)/out/file.cpp\
  $(ProjectName)/out/null.cpp\
  $(ProjectName)/out/print.cpp\
  $(ProjectName)/render/sdl_audio.cpp\
  $(ProjectName)/render/sdl_common.cpp\
  $(ProjectName)/render/sdl_video.cpp\
  $(ProjectName)/stream/mpeg_dash.cpp\
  $(ProjectName)/transform/audio_convert.cpp\
  $(ProjectName)/transform/video_convert.cpp\
  $(ProjectName)/utils/comparator.cpp\
  $(ProjectName)/utils/recorder.cpp\

LIB_MEDIA_OBJS:=$(MEDIA_SRCS:%.cpp=$(BIN)/%.o)
DEPS+=$(LIB_MEDIA_OBJS:%.o=%.deps)

CFLAGS+=
